# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grapher.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QLabel, QHBoxLayout
from PyQt5.QtCore import QObject, pyqtSlot, QPoint, QPointF
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QInputDialog
import math
import turtle
import random
from PIL import Image
from datetime import datetime

width = 700
height=700

class AnotherWindow(QWidget):
    def __init__(self):
        super().__init__()
        self.setGeometry(400,100,width,height)
        self.hbox = QHBoxLayout(self)


class Ui_MainWindow(QObject):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(309, 597)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dsbSpiralSpacing = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dsbSpiralSpacing.setGeometry(QtCore.QRect(50, 80, 62, 22))
        self.dsbSpiralSpacing.setDecimals(1)
        self.dsbSpiralSpacing.setMinimum(-100.0)
        self.dsbSpiralSpacing.setMaximum(100.0)
        self.dsbSpiralSpacing.setSingleStep(0.1)
        self.dsbSpiralSpacing.setProperty("value", -4.8)
        self.dsbSpiralSpacing.setObjectName("dsbSpiralSpacing")
        self.dsbSpiralTightness = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dsbSpiralTightness.setGeometry(QtCore.QRect(50, 120, 62, 22))
        self.dsbSpiralTightness.setDecimals(1)
        self.dsbSpiralTightness.setMinimum(3.0)
        self.dsbSpiralTightness.setObjectName("dsbSpiralTightness")
        self.pbSpiral = QtWidgets.QPushButton(self.centralwidget)
        self.pbSpiral.setGeometry(QtCore.QRect(40, 200, 93, 28))
        self.pbSpiral.setObjectName("pbSpiral")
        self.pbSpiral.clicked.connect(self.doGrapher1)
        self.pbSpirograph = QtWidgets.QPushButton(self.centralwidget)
        self.pbSpirograph.setGeometry(QtCore.QRect(30, 420, 93, 28))
        self.pbSpirograph.setObjectName("pbSpirograph")
        self.pbSpirograph.clicked.connect(self.doGrapher2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 80, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 120, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 240, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(110, 280, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(120, 330, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(120, 360, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.sbSpiralRevs = QtWidgets.QSpinBox(self.centralwidget)
        self.sbSpiralRevs.setGeometry(QtCore.QRect(70, 160, 42, 22))
        self.sbSpiralRevs.setProperty("value", 8)
        self.sbSpiralRevs.setObjectName("sbSpiralRevs")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(130, 160, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(120, 380, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.dsbSpiro_R = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dsbSpiro_R.setGeometry(QtCore.QRect(30, 290, 62, 22))
        self.dsbSpiro_R.setDecimals(1)
        self.dsbSpiro_R.setMinimum(3.0)
        self.dsbSpiro_R.setMaximum(500.0)
        self.dsbSpiro_R.setProperty("value", 220.0)
        self.dsbSpiro_R.setObjectName("dsbSpiro_R")
        self.dsbSpiro_r = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dsbSpiro_r.setGeometry(QtCore.QRect(30, 330, 62, 22))
        self.dsbSpiro_r.setDecimals(1)
        self.dsbSpiro_r.setMinimum(3.0)
        self.dsbSpiro_r.setProperty("value", 65.0)
        self.dsbSpiro_r.setObjectName("dsbSpiro_r")
        self.dsbSpiro_l = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dsbSpiro_l.setGeometry(QtCore.QRect(30, 370, 62, 22))
        self.dsbSpiro_l.setDecimals(1)
        self.dsbSpiro_l.setMinimum(0.1)
        self.dsbSpiro_l.setMaximum(1.0)
        self.dsbSpiro_l.setProperty("value", 1.0)
        self.dsbSpiro_l.setObjectName("dsbSpiro_l")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 309, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Grapher"))
        self.pbSpiral.setText(_translate("MainWindow", "Spiral"))
        self.pbSpirograph.setText(_translate("MainWindow", "Spirograph"))
        self.label.setText(_translate("MainWindow", "Spiral"))
        self.label_2.setText(_translate("MainWindow", "Rev Spacing"))
        self.label_3.setText(_translate("MainWindow", "Tightness"))
        self.label_4.setText(_translate("MainWindow", "Spirograph"))
        self.label_5.setText(_translate("MainWindow", "Large Radius"))
        self.label_6.setText(_translate("MainWindow", "Small Radius"))
        self.label_7.setText(_translate("MainWindow", "Pen tip from"))
        self.label_8.setText(_translate("MainWindow", "Revs"))
        self.label_9.setText(_translate("MainWindow", "Small Circle Center"))

    def show_new_window(self):
        self.w = AnotherWindow()
        self.label = QtWidgets.QLabel()
        canvas = QtGui.QPixmap(width, height)
        canvas.fill(Qt.white)
        self.label.setPixmap(canvas)
        self.painter = QtGui.QPainter(self.label.pixmap())
        self.w.hbox.addWidget(self.label)
        self.w.setLayout(self.w.hbox)
        R, k, l = self.R, self.spiro.k, self.l
        if self.spiro.graph == 1:
            polar = self.spiro.polar
        for i in range(0, 360 * self.spiro.nRot + 1, self.spiro.step):
            a = math.radians(i)
            if self.spiro.graph == 2.0:
                x = R * ((1 - k) * math.cos(a) + l * k * math.cos((1 - k) * a / k)) + self.spiro.xc
                y = R * ((1 - k) * math.sin(a) - l * k * math.sin((1 - k) * a / k)) + self.spiro.yc
            else:
                self.spiro.polar = self.r + R * a
                x = self.spiro.polar * math.cos(a) + self.spiro.xc
                y = self.spiro.polar * math.sin(a) + self.spiro.yc
            self.painter.drawLine(QPointF(self.spiro.startPoint.x(), self.spiro.startPoint.y()), QPointF(x, y))
            self.spiro.startPoint = QPointF(x,y)
        self.painter.end()
        self.w.show()

    @pyqtSlot()
    def doGrapher1(self):
        self.R = self.dsbSpiralSpacing.value()
        self.r = self.dsbSpiralTightness.value()
        self.l = self.sbSpiralRevs.value()
        #grapher_main(1, self.R, self.r, self.l)
        params = [1, self.R, self.r, self.l]
        self.spiro = Spiro(width/2, height/2, *params)
        self.show_new_window()

    def doGrapher2(self):
        self.R = self.dsbSpiro_R.value()
        self.r = self.dsbSpiro_r.value()
        self.l = self.dsbSpiro_l.value()
        params = [2, self.R, self.r, self.l]
        self.spiro = Spiro(width/2, height/2, *params)
        self.show_new_window()


# A class that makes a spirograph
class Spiro:
    # constructor
    def __init__(self, xc, yc, graph, R, r, l):
        # set step in degrees
        self.step = 5
        # set drawing complete flag
        self.drawingComplete = False
        # set parameters
        self.setparams(xc, yc, graph, R, r, l)
        # initialize drawing
        self.restart()

    # set parameters
    # if spiral, graph= 1.0, polar = r + R * theta, l = revs
    def setparams(self, xc, yc, graph, R, r, l):
        # spirograph parameters
        self.xc = xc
        self.yc = yc
        self.R = int(R)
        self.r = int(r)
        self.l = l
        self.graph = graph
        # reduce r/R to smallest form by dividing with GCD
        gcdVal = math.gcd(self.r, self.R)
        self.nRot = self.r // gcdVal
        if graph == 1.0:
            self.nRot = l
        # get ratio of radii
        self.k = r / float(R)
        # set color

        # current angle
        self.a = 0

    # restart drawing
    def restart(self):
        # set flag
        self.drawingComplete = False
        # go to first point
        R, k, l = self.R, self.k, self.l
        a = 0.0
        if self.graph == 2.0:
            x = R * ((1 - k) * math.cos(a) + l * k * math.cos((1 - k) * a / k)) + self.xc
            y = R * ((1 - k) * math.sin(a) - l * k * math.sin((1 - k) * a / k)) + self.yc
        else:
            self.polar = self.r + R * a
            x = self.polar * math.cos(a) + self.xc
            y = self.polar * math.sin(a) + self.yc
        self.startPoint = QPointF(x, y)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
